name: helmet_vehicle_detection
description: "A helmet detection app"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  flutter_dotenv: ^5.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    
  fonts:
    - family: SF-Pro
      fonts:
        - asset: 'fonts/SF-Pro-Display-Bold.otf'
          weight: 700
        - asset: 'fonts/SF-Pro-Display-Medium.otf'
          weight: 500
        - asset: 'fonts/SF-Pro-Display-Regular.otf'
          weight: 400
        - asset: 'fonts/SF-Pro-Display-SemiBold.otf'
          weight: 600
          
    - family: Dongle
      fonts:
        - asset: 'fonts/Dongle-Regular.ttf'
          weight: 500
        - asset: 'fonts/Dongle-Light.ttf'
          weight: 400
        - asset: 'fonts/Dongle-Bold.ttf'
          weight: 600

    - family: Quicksand
      fonts:
        - asset: 'fonts/Quicksand-Bold.ttf'
          weight: 700
        - asset: 'fonts/Quicksand-SemiBold.ttf'
          weight: 600
        - asset: 'fonts/Quicksand-Medium.ttf'
          weight: 500
        - asset: 'fonts/Quicksand-Regular.ttf'
          weight: 400
        - asset: 'fonts/Quicksand-Light.ttf'
          weight: 300
        
    